### ISSUE TITLE
Initialise the plugin without opening it?

### ISSUE THREAD

**Issue by TheKashe** [Dani3lSun/apex-plugin-spotlight#4]
Is it possible to initialise the plugin without opening it and then open it explicitly with a click?

E.g., put the DA on the page load event and let it load data without opening the dialog. Then a click on a button would trigger the dialog.

I could figure out the first part with some minor modifications to the plugin js, but I can't find an obvious way to open the dialog if it's not hosted in a button DA.

**Comment by Dani3lSun** [comment]
This should be the default, the plugin doesn't do an "auto open"...
Here you will find a simple demo show casing the plugin:
https://github.com/Dani3lSun/apex-plugin-spotlight/releases/tag/v.1.4.1
