### ISSUE TITLE
How to call this plugin by pressing a button on entry list?

### ISSUE THREAD

**Issue by mathiasmaciel97** [Dani3lSun/apex-plugin-spotlight#5]
I want to do a similar action like on the demo page. You display the plugin when the button **Spotlight Search** is pressed, that button is on breadcrumb bar but I want replicate that action on the button **Buscar** next to _APP USER_ and _LOGOUT_ buttons.
![Capture](https://user-images.githubusercontent.com/39440207/55160776-77b7d480-513a-11e9-96ae-2e776b999caf.PNG)

**Comment by nikitsky** [comment]
@mathiasmaciel97: You can achieve this by the following:
1. Add an unique class name to your Buscar menu item (using the User Defined Attribute  #A02#), e.g. b-spotlight
2. Create a dynamic action 'Click' on the page 0 with the Selection Type: jQuery Selector, the jQuery Selector: `.b-spotlight`
3. Add action for the DA: APEX Spotlight Search and provide your settings. 

Regards,
Valentine

**Comment by mathiasmaciel97** [comment]
@nikitsky could you show me how to do each step?
I can't interpret the step 1 where I've to add an unique class by using the _**User Defined Attribute**_
Regards.

**Comment by nikitsky** [comment]
@mathiasmaciel97 go to the application Shared Components -> Navigation Bar List -> Desktop Navigation Top Bar (or how do you named it) -> Buscar (your target list entity)
And than, take a look into the screenshot: 
<img width="1102" alt="Screenshot 2019-04-23 at 20 51 25" src="https://user-images.githubusercontent.com/2596018/56611442-b6419180-6609-11e9-852e-fec6f84a14eb.png">

**Comment by mathiasmaciel97** [comment]
@nikitsky it's look like this, I think is a little bit different:
![01](https://user-images.githubusercontent.com/39440207/56611973-24be2980-65e1-11e9-8343-00ec19d6a9b7.png)

**Comment by mathiasmaciel97** [comment]
@nikitsky  I put the class _`b-spotlight`_ as you mentioned first on the 2 box and it works!
Thanks for the patience, you're awesome!

**Comment by mathiasmaciel97** [comment]
@nikitsky  I put the class _`b-spotlight`_ as you mentioned first on the 2 box and it works!
Thanks for the patience, you're awesome!

**Comment by nikitsky** [comment]
> @nikitsky it's look like this, I think is a little bit different:
> ![01](https://user-images.githubusercontent.com/39440207/56611973-24be2980-65e1-11e9-8343-00ec19d6a9b7.png)

My screenshot was made from APEX 19.1, yours from a previous version. But you got the idea ;)
