### ISSUE TITLE
SQL Query can be replaced with "PLSQL Function returning SQL Query"

### ISSUE THREAD

**Issue by SNiklas** [Dani3lSun/apex-plugin-spotlight#7]
For better maintainability - also with regard to the distribution of the plugin over several applications with the same data - it would be useful if the "Data Source SQL" query could optionally be replaced by a PLSQL function that returns an SQL query.

**Comment by Dani3lSun** [comment]
Atm you can use for example a view layer to hide complex SQL and make it more reusable or use SQL with e.g. a table / pipelined function to achieve some dynamically created dataset...In my opinion there is no need to use a pl/sql function which returns a SQL statement...
