### ISSUE TITLE
How to return results set to other input ( interactive Report ) 

### ISSUE THREAD

**Issue by etaygudai** [Dani3lSun/apex-plugin-spotlight#8]
Hello Daniel Sun,

Thank you again for those great plugins you write.

Small question : I have bit customized your apexspotlight plugin to fit my needs, yet, I just wonder ( before playing too much around with code ) **### is there any easy way to place the results list in my input, rather the in dialog one ?** ( **I would like to return results set to Interactive Report input** ).

Attach below is my implementation 

![MyDialog1](https://user-images.githubusercontent.com/18305794/60794693-faf1b900-a172-11e9-8fef-887364327620.jpg)
![MyDialog2](https://user-images.githubusercontent.com/18305794/60794694-fb8a4f80-a172-11e9-8d2a-076bc078a5b1.jpg)

**Comment by Dani3lSun** [comment]
Hi @etaygudai 

if you want to set the search field of an IR and execute the search afterwords you could do the following:
1) Give your IR region a static id, e.g. TEST_IR
2) Define a JavaScript function on that page, which set the input and presses the search button of IR

```
function searchIR(pStaticRegionId, pSearchTerm) {
  $('input#' + pStaticRegionId + '_search_field').val(pSearchTerm);
  $('button#' + pStaticRegionId + '_search_button').click();
}
```
3) Add a new static entry to the spotlight search SQL query 

```
-- static entry (link contains ~SEARCH_VALUE~)--> set item client side
SELECT 'Set Search field of IR' AS title,
       'Set search field of Interactive Report' AS description,
       'javascript:searchIR(''TEST_IR'',''~SEARCH_VALUE~'');' AS link,
       'fa-search' AS icon
  FROM dual
```

That should be it! :)
